version: 3.7

services:
    nextcloud-db:
    nextcloud:
    nginx-proxy:
    letsencrypt-proxy-companion:
    mattermost:
    mattermost-notifications:
    openproject1:
    openproject2:
    openprojectN:
    collabora:
    


volumes:


networks: 
    nginx_network:
        # nginx-proxy and letsencrypt 
    nextcloud_network:
        # nextcloud front & backend
    mattermost_network:
        # Mattermost server & notification server
    backend_network:
        # For all integration api workers to communicate and replicate changes accross services
    