version: '3'  

services:

  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=j6mIMCpGoL9ofKwGisLeTMU5 # Definitely change this for deployment
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=WhC9PLlExJ04sV7CbxGCtNkZ # Definitely change this for deployment
      - MYSQL_DATABASE=nextcloud_db
    restart: unless-stopped
            
                
  app:
    image: nextcloud:latest
    hostname: nextcloud.projectmobi.io
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    environment:
      # for nginx proxy and letsencrypt
      - VIRTUAL_HOST=nextcloud.projectmobi.io
      - LETSENCRYPT_HOST=nextcloud.projectmobi.io
      - LETSENCRYPT_EMAIL=webmaster@projectmobi.io

      # Nextcloud env vars required for autoconfig
      - NEXTCLOUD_ADMIN_USER=nextcloud_admin
      - NEXTCLOUD_ADMIN_PASSWORD=7hNLl4sCCtC9PGVbxWExJk0Z # Definitely change this for deployment
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.projectmobi.io
      - NEXTCLOUD_UPDATE=1
      - MYSQL_HOST=db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=WhC9PLlExJ04sV7CbxGCtNkZ # Definitely change this for deployment
      - MYSQL_DATABASE=nextcloud_db  
    restart: unless-stopped
  
      
volumes:
  nextcloud:
  db:
         
      
networks:
    default:
        external:
            name: nginx-proxy
  