
version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
        - ADMINER_DESIGN=galkaev
        - ADMINER_DEFAULT_SERVER=db
        - VIRTUAL_HOST=adminer.projectmobi.io
        - VIRTUAL_PORT=8080
        - LETSENCRYPT_HOST=adminer.projectmobi.io
        - LETSENCRYPT_EMAIL=webmaster@projectmobi.io

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment: 
      - VIRTUAL_HOST=grafana.projectmobi.io
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.projectmobi.io
      - LETSENCRYPT_EMAIL=webmaster@projectmobi.io
    


networks:
    default:
        external:
            name: nginx-proxy
    

